### PR TITLE
Resolve a few TODOs

### PR DESCRIPTION
**Pull request by cletusw**
- Proxy the actual exit value from Flow
- Retain colors in the output
- Provide link to installation guide if Flow dependency not found

### CODE REVIEW

**Comment by jareware** [comment]
Really cool, thanks!

About 668737b30fdc6e255f59264a1f34ad0f7b02b59d and using `--strip-root`, though, would it still be a better idea to match the output of the corresponding Flow command _exactly_? Since without extra switches the output is (for reasons unknown) with absolute paths.

Maybe if we just proxy any switches to Flow, so that you'd get that behaviour with `$ flotate check --strip-root`. What do you think?

**Comment by cletusw** [comment]
You're absolutely right. This was just a cop out because I couldn't get node to retain terminal colors while still allowing processing on the string. If you want I can back out the colors thing. You'd still get the helpful install link and proxying of Flow's exit code.

**Comment by jareware** [comment]
Hmm, I think that's why I gave up on my first quick try (to retain colors) also...

I'd love both features, but sure, it might make sense to pull in the install link & exit code part _now_, and get back to the colors in another PR for example.

**Comment by jareware** [comment]
On second thought, I think terminal colors are nicer than having the full paths in the default output!

**Comment by jareware** [comment]
Thanks a lot for your contribution! :bow:

**Comment by cletusw** [comment]
Awesome! Glad to help.

**Pull request merged**
